<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Btn_AddFile_UploadSummary</name>
   <tag></tag>
   <elementGuidId>53c8b5b0-38cd-4bf6-8e81-971f2bbcd7c6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;loadShiftStrategyUpload_files&quot;]/div/button
</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <type>Main</type>
      <value>//*[@id=&quot;loadShiftStrategyUpload_files&quot;]/div/button</value>
   </webElementXpaths>
</WebElementEntity>
