<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>tbody_Table_NonSmoke</name>
   <tag></tag>
   <elementGuidId>850d8475-ad73-49ff-bf11-0904db803684</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;nonSmokePolicy_files&quot;]/table/tbody</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <value>//*[@id=&quot;nonSmokePolicy_files&quot;]/table/tbody</value>
   </webElementXpaths>
</WebElementEntity>
