<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>tbody_Table_SWM_Lamps</name>
   <tag></tag>
   <elementGuidId>28366fb7-96cf-4b42-aca7-1709beef4ed4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;swm_dispoBatteriesAndLamps_files&quot;]/table/tbody</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <value>//*[@id=&quot;swm_dispoBatteriesAndLamps_files&quot;]/table/tbody</value>
   </webElementXpaths>
</WebElementEntity>
