<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>tbody_Table_PerformancePeriods</name>
   <tag></tag>
   <elementGuidId>1168957a-2a9b-4216-8384-552df5ddce0b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;perforPeriodsTblDocs_files&quot;]/table/tbody</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <value>//*[@id=&quot;perforPeriodsTblDocs_files&quot;]/table/tbody</value>
   </webElementXpaths>
</WebElementEntity>
