<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>tbody_AddFile_SA</name>
   <tag></tag>
   <elementGuidId>597a81dd-e09c-4812-8c57-d03fd9972027</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;siteAssessmentUpload_files&quot;]/table/tbody</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <type>Main</type>
      <value>//*[@id=&quot;siteAssessmentUpload_files&quot;]/table/tbody</value>
   </webElementXpaths>
</WebElementEntity>
