<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h3_Status</name>
   <tag></tag>
   <elementGuidId>f16ed9ef-2fbb-49f3-85f9-7baa22882452</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;2b3d64238fc5cfa3eedcc40fe47531db&quot;]/div[4]/div/div/h3</value>
      </entry>
      <entry>
         <key>BASIC</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <type>Main</type>
      <value>//*[@id=&quot;2b3d64238fc5cfa3eedcc40fe47531db&quot;]/div[4]/div/div/h3</value>
   </webElementXpaths>
</WebElementEntity>
