<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h3_Status</name>
   <tag></tag>
   <elementGuidId>e278710e-6410-4f81-9fc9-6c288a041cf2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;5bfe6c8d612c370eaf910e2975869992&quot;]/div[4]/div/div/h3</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <type>Main</type>
      <value>//*[@id=&quot;5bfe6c8d612c370eaf910e2975869992&quot;]/div[4]/div/div/h3</value>
   </webElementXpaths>
</WebElementEntity>
