<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>tbody_Table_EventsCalc</name>
   <tag></tag>
   <elementGuidId>22816b3e-5505-487a-afd3-cbe3104ca5df</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;rainFallEventsCalc_files&quot;]/table/tbody</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <value>//*[@id=&quot;rainFallEventsCalc_files&quot;]/table/tbody</value>
   </webElementXpaths>
</WebElementEntity>
