<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>tbody_Table_EPP_Purchased</name>
   <tag></tag>
   <elementGuidId>3fa3d5f2-eda9-4876-9707-fa1e618ea6d3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;epp_mostPurchased_files&quot;]/table/tbody</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <value>//*[@id=&quot;epp_mostPurchased_files&quot;]/table/tbody</value>
   </webElementXpaths>
</WebElementEntity>
