<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>tbody_Table_Basebuilding</name>
   <tag></tag>
   <elementGuidId>381e1a42-f3bf-4764-9e96-7286cd94103a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;baseBuildingElem_files&quot;]/table/tbody</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <type>Main</type>
      <value>//*[@id=&quot;baseBuildingElem_files&quot;]/table/tbody</value>
   </webElementXpaths>
</WebElementEntity>
