<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>tbody_Table_SWM_Office</name>
   <tag></tag>
   <elementGuidId>5e9dedc1-1ab1-4b71-b6d4-0d5c2610d2be</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;swm_officeEquiAppliances_files&quot;]/table/tbody</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <value>//*[@id=&quot;swm_officeEquiAppliances_files&quot;]/table/tbody</value>
   </webElementXpaths>
</WebElementEntity>
