<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>divval</name>
   <tag></tag>
   <elementGuidId>bc9c4449-2ef1-4177-bf41-762f90c18bf2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;d90d444c95d636d4faab7c72fc073cef&quot;]/div[4]/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <type>Main</type>
      <value>//*[@id=&quot;d90d444c95d636d4faab7c72fc073cef&quot;]/div[4]/div/div</value>
   </webElementXpaths>
</WebElementEntity>
