<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>tbody_Table_WeatherStrip</name>
   <tag></tag>
   <elementGuidId>1a337858-11af-47c2-bef6-645e61806c2f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;weatherStrippingAndSealingDocs_files&quot;]/table/tbody</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <value>//*[@id=&quot;weatherStrippingAndSealingDocs_files&quot;]/table/tbody</value>
   </webElementXpaths>
</WebElementEntity>
