<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_MarkReadyForReview</name>
   <tag></tag>
   <elementGuidId>086b25f0-14cf-44cc-b7d7-7177e3d66861</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//a[contains(text(),'Submit')])[8]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <type>Main</type>
      <value>(//a[contains(text(),'Submit')])[8]</value>
   </webElementXpaths>
</WebElementEntity>
