<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>tbody_Table_ScaledSite</name>
   <tag></tag>
   <elementGuidId>84501077-a200-445b-9b57-c0aa8bd360c4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;smokeZoneDocs_files&quot;]/table/tbody</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <value>//*[@id=&quot;smokeZoneDocs_files&quot;]/table/tbody</value>
   </webElementXpaths>
</WebElementEntity>
