<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe</name>
   <tag></tag>
   <elementGuidId>f542e9b9-3ab3-478b-b292-0cdfaa8c7607</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='creditHtmlForm']/iframe</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://leedonline-api-stg.usgbc.org/Credit/form/UlhzUnBtczBac05ZTzZFK0k4UkMyRXhkcFIvRU5JZjNNUDMrNWd2aFI1eTNDRFpYUzEwTzNmN081SWd3WU1OdUlubU5VQURaZG9yUmNjejNZamd3STZNT3BEMmJxYWlMWXVXcm45bjBMc3ZJdHNOYzFnWTFnejlXNEt3Nk9wM1JNKzhKTE04bGtRZjhQSnFEMGZGVjNCK3lXT0dDc2VzQU1PcnhlQnRzUTJiU0pFVEZaWFBJeEdyQ3gxd2UyQ2VZTko5WGh1MWx6S2NEVTM4WEk4bkRIODhRd0ZSNmM0WjVNREdIUXNEYUswdkJkUFBRM2NlLzN5YW5GL3ZscGUrTmVZcHdxbFRtT1JyNzdKS3JVcDFBd0ZhaGRtREtCZ0VVNFBsSU5QbHJmL1hKNElQYlJvT1pUVnpXVU9qME5KNWFHMW1vcXVJRHROSi9FZU4wd3pueFNuQmdESWUzSTZJeW5EU0I0WGRXaS9vPSRiOEhGRFFQb3N0bz0?initialWidth=916&amp;childId=creditHtmlForm&amp;parentTitle=LEED%20Online&amp;parentUrl=https%3A%2F%2Fleedonline-stg.usgbc.org%2Fform%2FsimpleForm%3F__creditId%3DEBCTEQ106L-1000163341%26__creditShortId%3DEQ106%26creditHash%3De689c692628aa7524f11aa2761d8b121%26projectId%3D1000163341</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>100%</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>no</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>marginheight</name>
      <type>Main</type>
      <value>0</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>1588px</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;creditHtmlForm&quot;)/iframe[1]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <value>//div[@id='creditHtmlForm']/iframe</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Loading...'])[1]/following::iframe[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Credit library'])[1]/following::iframe[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Feedback'])[1]/preceding::iframe[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <value>//iframe</value>
   </webElementXpaths>
</WebElementEntity>
