<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe</name>
   <tag></tag>
   <elementGuidId>f0210937-65e7-4f58-9e79-92babf6836c2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='creditHtmlForm']/iframe</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://leedonline-api-stg.usgbc.org/Credit/form/VFlGdFZuZm50TmFmSkhBUVRRUTBabEIrNEJDN3BWS1pVZThWT0YzU2UxZ3dyRFdpbjVmSHErUmRZaWRPUSt1YmlVWlVJcmJMNkRCL2tTR2ZLTExwRnBNWG84OUplekcwYVRSVDhzQ0JJYWwzNndaSFhocTh2NTRlL0NybDY5TzBIY3V3YXUrWWU0RTFYY1NZMk1VaDFoZkdxWTBjdkFWSndvdS95Z1hKaklRMDB6Q29zSWdvMm80Zmt5U2FWM20vczBsN0dCTE54RmZMMnJLZnFFTUxJampNbUpkK1R6Mi9UaU1MZ3ZTY2pKL1ZUQWd1bGhvNUZqb3poU0htc3crbVlxVDBzUS9xekFRNHEyejlkVjI0dzExdGR6MytQYy8wOGl2dHB4OW4rQ01hdnh3U3ZtV0FnYTNGUFY1aER1TktJRkFFY2wyU0ZibnI2cXJsanVYZEVRdllsaFlkNjBOM0wrUEZ4NVZoU0dZPSRyNEpQSUNFcTQ0WT0?initialWidth=916&amp;childId=creditHtmlForm&amp;parentTitle=LEED%20Online&amp;parentUrl=https%3A%2F%2Fleedonline-stg.usgbc.org%2Fform%2FsimpleForm%3F__creditId%3DEBCTMR106L-1000160337%26__creditShortId%3DMR106%26creditHash%3D13da86e7dd6566567c6feb21b0d7b6ed%26projectId%3D1000160337</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>100%</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>no</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>marginheight</name>
      <type>Main</type>
      <value>0</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>1316px</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;creditHtmlForm&quot;)/iframe[1]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='creditHtmlForm']/iframe</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Loading...'])[1]/following::iframe[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Credit library'])[1]/following::iframe[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Feedback'])[1]/preceding::iframe[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
   </webElementXpaths>
</WebElementEntity>
