<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>divval</name>
   <tag></tag>
   <elementGuidId>c1756e1c-3f1d-45cc-9e66-864ed242406c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;f5f2e39fa778516b2683d65361757a3e&quot;]/div[4]/div/div</value>
      </entry>
      <entry>
         <key>BASIC</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <type>Main</type>
      <value>//*[@id=&quot;f5f2e39fa778516b2683d65361757a3e&quot;]/div[4]/div/div</value>
   </webElementXpaths>
</WebElementEntity>
