<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe</name>
   <tag></tag>
   <elementGuidId>6c5a765e-33a1-4a64-a170-0c84e592b513</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;creditHtmlForm&quot;]/iframe</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://leedonline-api-stg.usgbc.org/Credit/form/NmFNdGtPNnhRL3FEZHc3SWlhMDVCOFVEUDNKS2RBSWx1RGJ0MWJCTXNxQnBPNzc3V251STliallKNUM4OGNzU2t0QlZrSjFzeFR1Z0tzRjZYZGU3RTlIWWRIY0xySmd3UXFWZmx3R1pjWWRlMWw1M3IwaUFHNUxuejZZUkVXbkJNbitJbEcxeHd6SndaemQvblUwdFZLMFYyQitXQ01tdTlqRDl0Z0s0cm04S1NES0hoZ1RobkZwb25ta1c0YTRvSmI5Sm9iUk1tWkJvOUdXUnFjTVUrN3JkdWE3Z3FpWThMb0hLQXZISnRrOS9PR0hsR284eUlWbVVxYit0alJYL09SU1FsZmthUDdnaVArcTZHTFJXSFFhSkQzdWdkQWs4RUpmTmJKQS83eloySTZXK1RYZkNaSGllc244UmYzall1VlhuY09SZVJlVU9HdnhubVBvTlZRZ0lYK1IxRElsY0tNWWFHYVdLZk0wPSQwSDJDbmJ6RGNTMD0?initialWidth=916&amp;childId=creditHtmlForm&amp;parentTitle=LEED%20Online&amp;parentUrl=https%3A%2F%2Fleedonline-stg.usgbc.org%2Fform%2FsimpleForm%3F__creditId%3DEBCTSS118L-1000163411%26__creditShortId%3DSS118%26creditHash%3Df5f2e39fa778516b2683d65361757a3e%26projectId%3D1000163411</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>100%</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>no</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>marginheight</name>
      <type>Main</type>
      <value>0</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>665px</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;creditHtmlForm&quot;)/iframe[1]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//*[@id=&quot;creditHtmlForm&quot;]/iframe</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Loading...'])[1]/following::iframe[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Credit library'])[1]/following::iframe[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Feedback'])[1]/preceding::iframe[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
   </webElementXpaths>
</WebElementEntity>
