<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_MarkReadyForReview</name>
   <tag></tag>
   <elementGuidId>1989677b-ab4d-42b3-a1bd-26a3f89ee947</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//a[contains(text(),'Submit')])[21]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <type>Main</type>
      <value>(//a[contains(text(),'Submit')])[21]</value>
   </webElementXpaths>
</WebElementEntity>
